### ISSUE TITLE
Add configuration to allow for other options to be passed to `karma start`

### ISSUE THREAD

**Issue by blake-mealey** [black-trooper/quick-karma#1]
I would really like to use this extension but I can't because `karma start` is not sufficient for my use case. Ideally, I would like to use `npm run test:debug` but at the very least, I need to be able to run `karma start --no-single-run karma.debug.conf.js`.

Please add some configuration to allow me to change/add to the command that is run. I think either allowing the user to specify the exact command, or having a couple parameters like "options" which I could use for "--no-single-run" and "config file" like "karma.debug.conf.js"

If you need me to I can attempt a PR

**Comment by black-trooper** [comment]
@blake-mealey 
`quick-karma` is an extension that simply executes `karma run --- grep =" xxxx "` without entering a command, so you can start karma in any way.
